# -*- coding: utf-8 -*-
"""kpiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wZjxmBeBJzU7Wab6HEj4LMCJMHdGtr9

**Problem Statement**

Sales teams often lack a clear, data-driven understanding of regional performance, making it difficult to identify growth opportunities and optimize resources. This project aims to analyse and visualize regional sales data to uncover trends, evaluate profitability, and support strategic decision-making.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sheets=pd.read_excel('/content/Regional Sales Dataset For Project.xlsx',sheet_name=None)

#Assigning dataframe to sheets
df_sales=sheets['Sales Orders']
df_customers=sheets['Customers']
df_products=sheets['Products']
df_regions=sheets['Regions']
df_state_reg=sheets['State Regions']
df_budgets=sheets['2024 Budgets']

df_sales.shape

df_sales.sample(5)

df_products.sample(5)

df_state_reg.iloc[0:5]

df_state_reg.columns = df_state_reg.iloc[0]
df_state_reg = df_state_reg[1:]
df_state_reg.reset_index(drop=True, inplace=True)
df_state_reg.columns = ["State Code", "State", "Region"]

df_state_reg.iloc[0:5]

df_sales.isnull().sum()

df_products.isnull().sum()

df_regions.isnull().sum()

"""**Data Cleanign and Wrangling**"""

# Merge with Customers
df = df_sales.merge(
    df_customers,
    how='left',
    left_on='Customer Name Index',
    right_on='Customer Index'
)

# Merge with Products
df = df.merge(
    df_products,
    how='left',
    left_on='Product Description Index',
    right_on='Index'
)

# Merge with Regions
df = df.merge(
    df_regions,
    how='left',
    left_on='Delivery Region Index',
    right_on='id'
)

# Merge with State Regions
df = df.merge(
    df_state_reg[["State Code","Region"]],
    how='left',
    left_on='state_code',
    right_on='State Code'
)

# Merge with Budgets
df = df.merge(
    df_budgets,
    how='left',
    on='Product Name'
)

# Clean up redundant columns
cols_to_drop = [
    'Customer Index', 'Index', 'id', 'State Code',
]
df = df.drop(columns=cols_to_drop, errors='ignore')

df.sample(5)

# Converting all column names to lowercase for consistency and easier access
df.columns = df.columns.str.lower()

# Display the updated list of column names
df.columns.values

# DROP UNNECESSARY COLUMNS & RENAME FOR CLARITY (with Region)

# 1) List only the columns you want to KEEP, now including the broader 'region'
cols_to_keep = [
    'ordernumber',        # unique order ID
    'orderdate',          # date when the order was placed
    'customer names',     # customer who placed the order
    'channel',            # sales channel (e.g., Wholesale, Distributor)
    'product name',       # product purchased
    'order quantity',     # number of units ordered
    'unit price',         # price per unit
    'line total',         # revenue for this line item (qty × unit_price)
    'total unit cost',    # company’s cost for this line item
    'state_code',         # two-letter state code
    'state',              # full state name
    'region',             # broader U.S. region (e.g., South, West)
    'latitude',           # latitude of delivery city
    'longitude',          # longitude of delivery city
    '2024 budgets'        # budget target for this product in 2024
]

# Subset the DataFrame to only these columns
df = df[cols_to_keep]

# 2) Rename to more Pythonic / self-explanatory names, including region
df = df.rename(columns={
    'ordernumber'      : 'order_number',   # case for consistency
    'orderdate'        : 'order_date',     # date of the order
    'customer names'   : 'customer_name',  # customer who placed it
    'product name'     : 'product_name',   # product sold
    'order quantity'   : 'quantity',       # units sold
    'unit price'       : 'unit_price',     # price per unit in USD
    'line total'       : 'revenue',        # revenue for the line item
    'total unit cost'  : 'cost',           # cost for the line item
    'state_code'       : 'state',          # two-letter state code
    'state'            : 'state_name',     # full state name
    'region'           : 'us_region',      # broader U.S. region
    'latitude'         : 'lat',            # latitude (float)
    'longitude'        : 'lon',            # longitude (float)
    '2024 budgets'     : 'budget'          # 2024 budget target (float)
})

# Display the cleaned DataFrame structure
df.sample(5)

df.columns.values

df.info()

"""**Feature Engineering**"""

#  Calculate total cost for each line item
df['total_cost'] = df['quantity'] * df['cost']

#  Calculate profit as revenue minus total_cost
df['profit'] = df['revenue'] - df['total_cost']

#  Calculate profit margin as a percentage
df['profit_margin_pct'] = (df['profit'] / df['revenue']) * 100

#  Extract full month name from order_date for labeling (e.g., 'January', 'February')
df['order_month_name'] = df['order_date'].dt.month_name()

#  Extract month number from order_date for correct sorting (1–12)
df['order_month_num'] = df['order_date'].dt.month

#  Display the updated DataFrame
df

"""# **Exploratory Analysis**
 **Monthly Sales Trend Over Time**
"""

# Convert order_date to monthly period (e.g., 2022-01, 2022-02)
df['order_month'] = df['order_date'].dt.to_period('M')

# Calculate total revenue for each month
monthly_sales = df.groupby('order_month')['revenue'].sum()

# Set figure size for clarity
plt.figure(figsize=(15,4))

# Plot the monthly sales trend with circle and navy line
monthly_sales.plot(marker='o', color='navy')

# Scale y-axis values to millions for readability
from matplotlib.ticker import FuncFormatter
formatter = FuncFormatter(lambda x, pos: f'{x/1e6:.1f}M')
plt.gca().yaxis.set_major_formatter(formatter)

# Add title and axis labels
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Revenue (Millions)')

# Rotate x-axis labels for better readability
plt.xticks(rotation=45)

# Adjust layout to prevent clipping
plt.tight_layout()
plt.show()

"""**Monthly Sales Trend (All Years Combined)**"""

# Filter out any 2025 orders
tf= df[df['order_date'].dt.year != 2025]
# exclude any partial-year data (i.e., January and February of 2025)
# so that the monthly totals aren’t skewed by an incomplete year.
# create df_ so don’t alter the original df.


# Group by month number and month name, sum revenue, then sort by month number
monthly_sales = (
    tf
    .groupby(['order_month_num', 'order_month_name'])['revenue']
    .sum()
    .sort_index()
)

# Plot setup
from matplotlib.ticker import FuncFormatter

plt.figure(figsize=(14, 4))
plt.plot(
    monthly_sales.index.get_level_values(1),  # X-axis: month names
    monthly_sales.values,                     # Y-axis: total revenue
    marker='o',                                # circle markers
    color='navy'                               # line color
)

# Scale y-axis values to millions for readability
formatter = FuncFormatter(lambda x, pos: f'{x/1e6:.1f}M')
plt.gca().yaxis.set_major_formatter(formatter)

# Add title and axis labels
plt.title('Overall Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Revenue (Millions)')

# Rotate x-axis labels for readability
plt.xticks(rotation=45)

# Adjust layout to prevent clipping
plt.tight_layout()

# Display the plot
plt.show()

"""**Top 10 Products by Revenue (in Millions)**"""

# Calculate total revenue for each product and convert values to millions
top_prod = df.groupby('product_name')['revenue'].sum() / 1_000_000
top_prod = top_prod.nlargest(10)

# Plot
plt.figure(figsize=(9, 4))
sns.barplot(
    x=top_prod.values,
    y=top_prod.index,
    hue=top_prod.index,   # tie hue to y
    palette='viridis',
    legend=False
)

plt.title('Top 10 Products by Revenue (in Millions)')
plt.xlabel('Total Revenue (in Millions)')
plt.ylabel('Product Name')
plt.tight_layout()
plt.show()

"""**Top 10 Products by Avg Profit Margin**"""

# Compute average profit per product and take the top 10
top_margin = (
    df.groupby('product_name')['profit']
      .mean()
      .sort_values(ascending=False)
      .head(10)
)

# Set the figure size for clarity
plt.figure(figsize=(9, 4))


sns.barplot(
    x=top_margin.values,
    y=top_margin.index,
    hue=top_margin.index,
    palette='viridis',
    legend=False
)

# Add title and axis labels
plt.title('Top 10 Products by Avg Profit Margin')
plt.xlabel('Average Profit Margin (USD)')
plt.ylabel('Product Name')

# Adjust layout and display
plt.tight_layout()
plt.show()

"""**Sales by Channel (Pie Chart)**"""

# Group revenue by sales channel and sort descending
chan_sales = df.groupby('channel')['revenue'].sum().sort_values(ascending=False)

# Set figure size for the pie chart
plt.figure(figsize=(5, 5))

# Plot pie chart with percentage labels and a defined start angle
plt.pie(
    chan_sales.values,
    labels=chan_sales.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=sns.color_palette('coolwarm')
)

# Add title for context
plt.title('Total Sales by Channel')

plt.tight_layout()

plt.show()

"""**Average Order Value Distribution**"""

# Calculate the total revenue for each order to get the order value
aov = df.groupby('order_number')['revenue'].sum()

# Set the figure size for better visibility
plt.figure(figsize=(12, 4))

# Plot a histogram of order values
plt.hist(
    aov,
    bins=50,
    color='skyblue',
    edgecolor='black'
)

# Add title and axis labels for context
plt.title('Distribution of Average Order Value')
plt.xlabel('Order Value (USD)')
plt.ylabel('Number of Orders')

# Adjust layout to prevent clipping
plt.tight_layout()

plt.show()

"""**Total Sales by US Region**"""

# Aggregate total sales by region (in millions)
region_sales = (
    df
    .groupby('us_region')['revenue']
    .sum()
    .sort_values(ascending=False)
    / 1e6
)


plt.figure(figsize=(10, 4))
sns.barplot(
    x=region_sales.values,
    y=region_sales.index,
    hue=region_sales.index,
    palette='Blues_r',
    legend=False
)


plt.title('Total Sales by US Region', fontsize=16, pad=12)
plt.xlabel('Total Sales (in Millions USD)', fontsize=12)
plt.ylabel('US Region', fontsize=12)
plt.xticks(rotation=0)
sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""**Top 10 by Revenue and Order Count**"""

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap
import numpy as np

# Calculate total revenue per customer
rev_per_customer = df.groupby('customer_name')['revenue'].sum().sort_values(ascending=False)


top_rev = rev_per_customer.iloc[:10]
bottom_rev = rev_per_customer.iloc[-10:]   #

custom_pink_palette = LinearSegmentedColormap.from_list(
    "custom_pink", ["#F2A0C4", "#A8337D"], N=10
)

# Create a figure with two side-by-side subplots
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# Plot 1: Top 10 customers by revenue (blue gradient)
sns.barplot(
    x=top_rev.values / 1e6,
    y=top_rev.index,
    hue=top_rev.index,
    palette='Blues_r',
    legend=False,
    ax=axes[0]
)
axes[0].set_title('Top 10 Customers by Revenue', fontsize=14)
axes[0].set_xlabel('Revenue (Million USD)', fontsize=12)
axes[0].set_ylabel('Customer Name', fontsize=12)

# Plot 2: Bottom 10 customers by revenue (custom purple gradient)
sns.barplot(
    x=bottom_rev.values / 1e6,
    y=bottom_rev.index,
    hue=bottom_rev.index,
    palette=[custom_pink_palette(i) for i in np.linspace(0, 1, 10)],
    legend=False,
    ax=axes[1]
)
axes[1].set_title('Bottom 10 Customers by Revenue', fontsize=14)
axes[1].set_xlabel('Revenue (Million USD)', fontsize=12)
axes[1].set_ylabel('Customer Name', fontsize=12)


sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""**Average Profit Margin by Channel**"""

#  Compute average profit margin percentage for each channel
channel_margin = (
    df.groupby('channel', as_index=False)['profit_margin_pct']
      .mean()
      .sort_values(by='profit_margin_pct', ascending=False)
)

plt.figure(figsize=(6, 4))

# Create the bar chart
colors = sns.color_palette('coolwarm', len(channel_margin))
sns.barplot(
    data=channel_margin,
    x='channel',
    y='profit_margin_pct',
    color=None
)

plt.gca().patches[:]

# Apply custom colors to each bar
for i, bar in enumerate(plt.gca().patches):
    bar.set_facecolor(colors[i])

plt.bar_label(
    plt.gca().containers[0],
    labels=[f"{v:.2f}%" for v in channel_margin['profit_margin_pct']],
    label_type='edge',
    padding=2,
    fontsize=9,
    fontweight='bold'
)

plt.title('Average Profit Margin by Channel', fontsize=14, weight='bold')
plt.xlabel('Sales Channel', fontsize=11)
plt.ylabel('Avg Profit Margin (%)', fontsize=11)

sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""**Top and Bottom 10 Customers by Revenue**"""

# Aggregate total revenue and unique order count per state
state_rev = (
    df.groupby('state_name')
      .agg(
          revenue=('revenue', 'sum'),
          orders=('order_number', 'nunique')
      )
      .nlargest(10, 'revenue')
      .reset_index()
)


colors = sns.color_palette('coolwarm', len(state_rev))


# Plot 1: Top 10 States by Revenue

plt.figure(figsize=(15, 4))
bars = plt.bar(
    state_rev['state_name'],
    state_rev['revenue'] / 1e6,
    color=colors,
    edgecolor='black'
)

plt.title('Top 10 States by Revenue', fontsize=12, weight='bold')
plt.xlabel('State', fontsize=11)
plt.ylabel('Total Revenue (Million USD)', fontsize=11)
plt.xticks(rotation=45, ha='right')

plt.bar_label(bars, labels=[f"{v/1e6:.2f}" for v in state_rev['revenue']], padding=2, fontsize=9, fontweight='bold')

sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(15, 4))
bars = plt.bar(
    state_rev['state_name'],
    state_rev['orders'],
    color=colors,
    edgecolor='black'
)

plt.title('Top 10 States by Number of Orders', fontsize=13, weight='bold')
plt.xlabel('State', fontsize=11)
plt.ylabel('Order Count', fontsize=11)
plt.xticks(rotation=45, ha='right')

plt.bar_label(bars, labels=[f"{v:,}" for v in state_rev['orders']], padding=2, fontsize=9, fontweight='bold')

sns.despine(left=True, bottom=True)
plt.tight_layout()
plt.show()

"""**Customer Segmentation: Revenue vs. Profit Margin**"""

summary = df.groupby('customer_name').agg(
    total_revenue=('revenue', 'sum'),
    total_profit=('profit', 'sum'),
    avg_margin=('profit_margin_pct', 'mean'),
    orders=('order_number', 'nunique')
)

# Convert revenue to millions
summary['total_revenue_m'] = summary['total_revenue'] / 1e6

plt.figure(figsize=(8, 5))

# Bubble chart with revenue in millions
sns.scatterplot(
    data=summary,
    x='total_revenue_m',
    y='avg_margin',
    size='orders',
    sizes=(20, 200),
    alpha=0.7
)

plt.title('Customer Segmentation: Revenue vs. Profit Margin')
plt.xlabel('Total Revenue (Million USD)')  # <-- updated label
plt.ylabel('Avg Profit Margin (%)')

plt.tight_layout()
plt.show()































